name: widget_tree_depth_counter_example
description: Widget to count the amount of nested widget tree, useful in the dynamic construction of the interface when it is important to know the depth of widget.
version: 0.0.1-alpha

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  widget_tree_depth_counter:
    path: ../

flutter:
  uses-material-design: true
